# Generated by Django 3.2.8 on 2021-11-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'managed': False, 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
