# Generated by Django 3.2.8 on 2022-08-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_document_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationDocIdReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'relation_doc_id_receipt',
                'managed': False,
            },
        ),
    ]
