# Generated by Django 3.2.8 on 2021-11-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryWork',
        ),
        migrations.DeleteModel(
            name='Coeficient',
        ),
        migrations.DeleteModel(
            name='Contragents',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentReceipt',
        ),
        migrations.DeleteModel(
            name='DocumentReceiptRef',
        ),
        migrations.DeleteModel(
            name='DocumentRef',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeWork',
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.DeleteModel(
            name='ReceiptDetail',
        ),
        migrations.DeleteModel(
            name='RegisterMaterialsMove',
        ),
        migrations.DeleteModel(
            name='RegisterMaterialsRemainder',
        ),
        migrations.DeleteModel(
            name='RegisterReceipt',
        ),
        migrations.DeleteModel(
            name='RegisterReceiptComposition',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
